name: Update README with GitHub Stats

on:
  push:
  schedule:
    - cron: '0 * * * *' # met à jour toutes les heures

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_STATS_TOKEN" https://github-readme-stats.vercel.app/api/top-langs/?username=Balerion14&count_private=true > top-langs-card.png

      - name: Commit and Push README
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update GitHub stats"
          git push
